import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Unrealvibe Admin",
  description: "Generated by Unrealvibe",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
        
      >
        <script
          dangerouslySetInnerHTML={{
            __html: `
      try {
        if (localStorage.theme === 'dark') {
          document.documentElement.classList.add('dark')
        }
      } catch {}
    `,
          }}
        />
        {children}
      </body>
    </html>
  );
}
